### ISSUE TITLE
Replace the term "entity" in help text

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/rabbit_hole#4]
In Backdrop we're trying to avoid the technical/conceptual term "entity" in the user interface. I guess this assumption is valid for Backdrop core. It would be however nice if we could find alternatives and replace the "entity" term in Rabbit Hole as well.

So far, I came across "entity" or "entities" in the help text of the *Rabbit Hole settings*, see the settings for users for example:

(1)

> Allow these settings to be overridden for individual **entities**
> If this is checked, users with the Administer Rabbit Hole settings for user account permission will be able to override these settings for individual **entities**.

Possible alternative:

> Allow these settings to be overridden for individual **user accounts**
> If this is checked, users with the Administer Rabbit Hole settings for user account permission will be able to override these settings for individual **user accounts**.

(2)

> What should happen when someone tries to visit an **entity** page for user account?

Possible alternative:

> What should happen when someone tries to visit a **user account page**?

Other suggestions?

**Comment by laryn** [comment]
@olafgrabienski I tried to make an adjustment here (in the latest dev version) that I hope is better!

**Comment by olafgrabienski** [comment]
@laryn Thank you! Can you point me to a commit where I can see the adjustments?

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/rabbit_hole/commit/1e0851d54a89b8c3761c9b09a59adb21458b3203

**Comment by olafgrabienski** [comment]
Thanks again! The text changes in descriptions et al. look good to me.
