### ISSUE TITLE
Add The First Wiki Page

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/rabbit_hole#6]
Currently, I don't see any wiki pages. As I go through setting up the module and poking around, I will create at least one page.

This issue is to discuss the initial wiki pages and what should or shouldn't go into them. Much better than re-editing the wiki a bunch of times. A collaborative Google doc could also be added to make initial editing/planning easier.

**Comment by alexfinnarn** [comment]
https://github.com/backdrop-contrib/rabbit_hole/wiki/Introduction

**Comment by laryn** [comment]
Adding an image for the wiki welcome page.

![rabbit-hole-content-type-config](https://user-images.githubusercontent.com/871421/106902749-c6334400-66be-11eb-9dea-7f4d6643c96e.jpg)
