### ISSUE TITLE
Document difference from core functionality

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/rabbit_hole#7]
Similar functionality has been added to core (in https://github.com/backdrop/backdrop-issues/issues/100 I believe), so it might be worth documenting in the README what this module provides outside of that...

**Comment by laryn** [comment]
Added to the README:

> ## Other options

> If you just need a simple way to prevent node content of a certain type from being displayed, you may not need Rabbit Hole. Backdrop core now provides a "Hide path display" option under the "Display settings" tab when configuring a content type. This causes a "Page not found" notice to display for users without a special permission to "View hidden paths."
